<?php

namespace Database\Seeders;

use App\Models\Departement;
use App\Models\Kompetensi;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class RealKaryawanSeeder extends Seeder
{
    /**
     * Data karyawan ASLI dari perusahaan (data bulan lalu), cuma 3
     * departemen terbanyak: PRD, PPR, MTC. Status pakai singkatan asli
     * perusahaan (SK/ST/NSK/NST/MG), bukan istilah kita sendiri.
     *
     * PENTING: nama departemen PPR itu TEBAKAN (cuma ada singkatan di
     * data asli) — kalau salah, tinggal ganti baris nama_departement
     * di bawah, tidak perlu ubah data karyawannya.
     */
    public function run(): void
    {
        $atasan = User::where('role', 'atasan')->first();

        if (! $atasan) {
            $this->command->error('Belum ada user Atasan. Jalankan DemoKaryawanSeeder dulu.');
            return;
        }

        $departemenNama = [
            'PRD' => 'Produksi',
            'PPR' => 'PPR',
            'MTC' => 'Maintenance',
        ];

        $dataKaryawan = [
            'PRD' => [
                ['nik' => '26069916', 'nama' => 'A. RIVI NURMANSYAH', 'status' => 'MG'],
                ['nik' => '12100056', 'nama' => 'AA SANDRI', 'status' => 'NST'],
                ['nik' => '26039909', 'nama' => 'ABDILLAH ZUPAR', 'status' => 'MG'],
                ['nik' => '11100251', 'nama' => 'ABDUL MUJID', 'status' => 'NST'],
                ['nik' => '25050389', 'nama' => 'ABDUR ROHMAN', 'status' => 'NST'],
                ['nik' => '11090216', 'nama' => 'ACHMAD DARMAWAN', 'status' => 'NST'],
                ['nik' => '12100058', 'nama' => 'ACHMAD FAUZIE', 'status' => 'NST'],
                ['nik' => '26059911', 'nama' => 'ADAM PRASASTA PUTRA', 'status' => 'MG'],
                ['nik' => '26059926', 'nama' => 'ADAM SATRIYO', 'status' => 'MG'],
                ['nik' => '25109901', 'nama' => 'ADE AZKA AZKIA OKTAVIAN', 'status' => 'MG'],
                ['nik' => '15020226', 'nama' => 'ADE DARMAN', 'status' => 'NST'],
                ['nik' => '11090503', 'nama' => 'ADE ROHILI', 'status' => 'NST'],
                ['nik' => '25073002', 'nama' => 'ADE SAPUTRA', 'status' => 'NSK'],
                ['nik' => '25109912', 'nama' => 'ADIF PRASETIYO', 'status' => 'MG'],
                ['nik' => '13090169', 'nama' => 'ADITYA HARTONO', 'status' => 'NST'],
                ['nik' => '12010266', 'nama' => 'AGUNG', 'status' => 'NST'],
                ['nik' => '25079918', 'nama' => 'AGUNG DWI MULYONO', 'status' => 'MG'],
                ['nik' => '26069923', 'nama' => 'AGUNG HARDIANSYAH', 'status' => 'MG'],
                ['nik' => '11100296', 'nama' => 'AGUS', 'status' => 'NST'],
                ['nik' => '26069921', 'nama' => 'AGUS NUR FISWANTO', 'status' => 'MG'],
                ['nik' => '12100059', 'nama' => 'AGUS TRIAWAN', 'status' => 'NST'],
                ['nik' => '26051201', 'nama' => 'AGUSTIAN RIZKI', 'status' => 'NSK'],
                ['nik' => '14100202', 'nama' => 'AHMAD ANWAR', 'status' => 'NST'],
                ['nik' => '25109917', 'nama' => 'AHMAD FABIAN RIFAI', 'status' => 'MG'],
                ['nik' => '12100120', 'nama' => 'AHMAD FAIZ', 'status' => 'NST'],
                ['nik' => '26029907', 'nama' => 'AHMAD FARHAN ZAELANI', 'status' => 'MG'],
                ['nik' => '26069901', 'nama' => 'AHMAD FAUZI', 'status' => 'MG'],
                ['nik' => '26049907', 'nama' => 'AHMAD NURROHMAN', 'status' => 'MG'],
                ['nik' => '25112605', 'nama' => 'AHMAD RAMDHANI', 'status' => 'NSK'],
                ['nik' => '12100060', 'nama' => 'AHMAD RIDWAN', 'status' => 'NST'],
                ['nik' => '11100242', 'nama' => 'AHMAD RIFAI', 'status' => 'NST'],
                ['nik' => '26049904', 'nama' => 'AHMAD TAJUDIN', 'status' => 'MG'],
                ['nik' => '11030241', 'nama' => 'AHMAD TAJUDIN', 'status' => 'NST'],
                ['nik' => '11110267', 'nama' => 'AJA', 'status' => 'NST'],
                ['nik' => '11080256', 'nama' => 'AJI SOPWAN RAHMAN', 'status' => 'NST'],
                ['nik' => '12080018', 'nama' => 'AKHMAD SYEKHU', 'status' => 'NST'],
                ['nik' => '26049901', 'nama' => 'ALDINO IBNU PANGESTU', 'status' => 'MG'],
                ['nik' => '26039921', 'nama' => 'ALFARIJI', 'status' => 'MG'],
                ['nik' => '26079916', 'nama' => 'ALFAT SARIFUDIN', 'status' => 'MG'],
                ['nik' => '5110020', 'nama' => 'ALI', 'status' => 'NST'],
                ['nik' => '26079901', 'nama' => 'ALI SAFUDIN', 'status' => 'MG'],
                ['nik' => '26039913', 'nama' => 'ALIF HILMAN MAULANA A', 'status' => 'MG'],
                ['nik' => '26069919', 'nama' => 'ALIF NURWAHID', 'status' => 'MG'],
                ['nik' => '25129903', 'nama' => 'ALTHAF ARARYA JEANENDA', 'status' => 'MG'],
                ['nik' => '12100061', 'nama' => 'AMALI', 'status' => 'NST'],
                ['nik' => '25119913', 'nama' => 'ANDHIKA MAULANA', 'status' => 'MG'],
                ['nik' => '11060248', 'nama' => 'ANDI MANSYUR', 'status' => 'NST'],
                ['nik' => '26029915', 'nama' => 'ANDI PRATAMA', 'status' => 'MG'],
                ['nik' => '9020003', 'nama' => 'ANDI RAHMAT HIDAYAT', 'status' => 'ST'],
                ['nik' => '25129901', 'nama' => 'ANDI SUPRIANTO', 'status' => 'MG'],
                ['nik' => '26049915', 'nama' => 'ANDIKA RAHMADIANSYA', 'status' => 'MG'],
                ['nik' => '25099902', 'nama' => 'ANDIKHA ARYAPUTRA', 'status' => 'MG'],
                ['nik' => '26069911', 'nama' => 'ANDREAN FEBRIANSA', 'status' => 'MG'],
                ['nik' => '25079915', 'nama' => 'ANDY EMILDANI', 'status' => 'MG'],
                ['nik' => '12120136', 'nama' => 'ANTO RIYATNI', 'status' => 'NST'],
                ['nik' => '11090506', 'nama' => 'ANTO SULISTIYO', 'status' => 'NST'],
                ['nik' => '12100114', 'nama' => 'ARI STYA PURWANTO', 'status' => 'NST'],
                ['nik' => '26079920', 'nama' => 'ARIEL FAJAR PRASETIO', 'status' => 'MG'],
                ['nik' => '26059914', 'nama' => 'ARIF AFRIANSYAH', 'status' => 'MG'],
                ['nik' => '11100233', 'nama' => 'ARIF SURAHMAN', 'status' => 'NST'],
                ['nik' => '25121701', 'nama' => 'ARIF TUNGGARA', 'status' => 'NSK'],
                ['nik' => '12100116', 'nama' => 'ARIS HERMAWAN', 'status' => 'NST'],
                ['nik' => '10100264', 'nama' => 'ARIS KURNIAWAN', 'status' => 'NST'],
                ['nik' => '26069933', 'nama' => 'ARIS PURNOMO', 'status' => 'MG'],
                ['nik' => '11090218', 'nama' => 'ARYEF MUSTOVA', 'status' => 'NST'],
                ['nik' => '11110243', 'nama' => 'ASEP SETIANA KARMIN', 'status' => 'NST'],
                ['nik' => '12120140', 'nama' => 'ASEP SUHENDAR', 'status' => 'NST'],
                ['nik' => '12100038', 'nama' => 'ASEP SURYANA', 'status' => 'NST'],
                ['nik' => '26059923', 'nama' => 'BAGAS AHMAD AL HAFIZ', 'status' => 'MG'],
                ['nik' => '26039919', 'nama' => 'BAGUS BAMBANG P', 'status' => 'MG'],
                ['nik' => '25129919', 'nama' => 'BAGUS PUTRA SETIAWAN', 'status' => 'MG'],
                ['nik' => '12100065', 'nama' => 'BAMBANG HERI MURYANTO', 'status' => 'NST'],
                ['nik' => '12080019', 'nama' => 'BAMBANG SUPRIYANTO', 'status' => 'NST'],
                ['nik' => '20010358', 'nama' => 'BENY HERMAWAN', 'status' => 'NST'],
                ['nik' => '22100606', 'nama' => 'BOWO DWI LAKSONO', 'status' => 'NSK'],
                ['nik' => '13060155', 'nama' => 'BRUARI NURFALAH ADHI', 'status' => 'NST'],
                ['nik' => '15030221', 'nama' => 'CAHYO PUTRO PRATOMO', 'status' => 'NST'],
                ['nik' => '26059903', 'nama' => 'CANDRA', 'status' => 'MG'],
                ['nik' => '26062904', 'nama' => 'CHANDRA', 'status' => 'NSK'],
                ['nik' => '24120401', 'nama' => 'CHENDY ZIHAN PRADANI', 'status' => 'NSK'],
                ['nik' => '25129904', 'nama' => 'D HAQ MUHAMAD DAVI', 'status' => 'MG'],
                ['nik' => '26079911', 'nama' => 'DAFIT NIKO CANDRA', 'status' => 'MG'],
                ['nik' => '26029921', 'nama' => 'DAMA DWI PURNAWAN', 'status' => 'MG'],
                ['nik' => '12100039', 'nama' => 'DANI TAUFIK HIDAYAT', 'status' => 'NST'],
                ['nik' => '24122304', 'nama' => 'DANU ADI PRADANA', 'status' => 'NSK'],
                ['nik' => '26069934', 'nama' => 'DANU SETIAWAN', 'status' => 'MG'],
                ['nik' => '12050303', 'nama' => 'DAPIT HERDIANA', 'status' => 'NST'],
                ['nik' => '12070014', 'nama' => 'DAWAM', 'status' => 'NST'],
                ['nik' => '22100604', 'nama' => 'DEBI AMANTO', 'status' => 'NSK'],
                ['nik' => '98110088', 'nama' => 'DEDE JUMHANA', 'status' => 'NST'],
                ['nik' => '12100121', 'nama' => 'DEDE SOPIAN', 'status' => 'NST'],
                ['nik' => '26029911', 'nama' => 'DEDEN ROMANSAH', 'status' => 'MG'],
                ['nik' => '12100053', 'nama' => 'DEDY PRASETIA', 'status' => 'NST'],
                ['nik' => '11100219', 'nama' => 'DENI SOPYANI', 'status' => 'NST'],
                ['nik' => '26079903', 'nama' => 'DERI NOPTRI YANA', 'status' => 'MG'],
                ['nik' => '100195', 'nama' => 'DES PARYANTO', 'status' => 'NST'],
                ['nik' => '26069904', 'nama' => 'DHIMAS ADI SAPUTRO', 'status' => 'MG'],
                ['nik' => '26049908', 'nama' => 'DIAGO', 'status' => 'MG'],
                ['nik' => '11090237', 'nama' => 'DIDI WIDARYA', 'status' => 'NST'],
                ['nik' => '15040261', 'nama' => 'DIDIT DIMAS RAMDANI', 'status' => 'NST'],
                ['nik' => '26019902', 'nama' => 'DIKI SAPUTRA', 'status' => 'MG'],
                ['nik' => '12100054', 'nama' => 'DIKI ZULKARNAEN', 'status' => 'NST'],
                ['nik' => '25069934', 'nama' => 'DIMAS AGENG SEPTIAN', 'status' => 'MG'],
                ['nik' => '25109903', 'nama' => 'DIMAS IMANNUDIN', 'status' => 'MG'],
                ['nik' => '12120139', 'nama' => 'DODIK APRIANTO', 'status' => 'NST'],
                ['nik' => '24090503', 'nama' => 'DWI IKHSAN FIRMANSYAH', 'status' => 'NSK'],
                ['nik' => '12030317', 'nama' => 'DWI NURWAHYONO', 'status' => 'NST'],
                ['nik' => '120204', 'nama' => 'DWI TATANG', 'status' => 'NST'],
                ['nik' => '11070263', 'nama' => 'EDDY', 'status' => 'NST'],
                ['nik' => '13070157', 'nama' => 'EDI SETYAWAN', 'status' => 'NST'],
                ['nik' => '99080105', 'nama' => 'EGUH PRASETYO', 'status' => 'NST'],
                ['nik' => '20147', 'nama' => 'EKO PRAYITNO', 'status' => 'NST'],
                ['nik' => '12100070', 'nama' => 'EKO TRIYONO', 'status' => 'NST'],
                ['nik' => '11100224', 'nama' => 'EKO WAHYUDI', 'status' => 'NST'],
                ['nik' => '26069928', 'nama' => 'ERIK MAULANA', 'status' => 'MG'],
                ['nik' => '25119904', 'nama' => 'ERIS ADI PUTRA PRATAMA', 'status' => 'MG'],
                ['nik' => '26059910', 'nama' => 'FAHRI HAFIFI', 'status' => 'MG'],
                ['nik' => '26029905', 'nama' => 'FAHRI NURPAUZI', 'status' => 'MG'],
                ['nik' => '25109907', 'nama' => 'FAISAL ABHIE SOFYAN', 'status' => 'MG'],
                ['nik' => '26059915', 'nama' => 'FAISAL DWI TAMA', 'status' => 'MG'],
                ['nik' => '12080025', 'nama' => 'FAJAR MAULIDIN HADI', 'status' => 'NST'],
                ['nik' => '26029901', 'nama' => 'FAJAR MUHAMMAD ALFIDHO', 'status' => 'MG'],
                ['nik' => '25109908', 'nama' => 'FAREL DESTA ARDANI', 'status' => 'MG'],
                ['nik' => '25129909', 'nama' => 'FARIZQI FATUR ROHMAN', 'status' => 'MG'],
                ['nik' => '26069902', 'nama' => 'FARREL JANUAR SETYADHI', 'status' => 'MG'],
                ['nik' => '25119914', 'nama' => 'FAZAR TIRTA HIDAYAT', 'status' => 'MG'],
                ['nik' => '26069931', 'nama' => 'FEBBY HIDAYAT', 'status' => 'MG'],
                ['nik' => '26079902', 'nama' => 'FEBRIANTO', 'status' => 'MG'],
                ['nik' => '12030299', 'nama' => 'FERY ANGGRIAWAN', 'status' => 'NST'],
                ['nik' => '22100402', 'nama' => 'FIRMAN SAPUTRA', 'status' => 'NSK'],
                ['nik' => '6100016', 'nama' => 'FITRI NUR AINI', 'status' => 'NST'],
                ['nik' => '11081221', 'nama' => 'FITRIA ATMOJO', 'status' => 'NST'],
                ['nik' => '25099917', 'nama' => 'FREDIKA ALDIANSYAH', 'status' => 'MG'],
                ['nik' => '26079917', 'nama' => 'FUAD HANAN NOVIANTO', 'status' => 'MG'],
                ['nik' => '26069920', 'nama' => 'GALAN ADE PRADANU', 'status' => 'MG'],
                ['nik' => '25089905', 'nama' => 'GALANG PRASETIOFEDI', 'status' => 'MG'],
                ['nik' => '15010225', 'nama' => 'GANDI IRAWANTO', 'status' => 'NST'],
                ['nik' => '25119905', 'nama' => 'GIBRAN AL GHIFARI ALI .A', 'status' => 'MG'],
                ['nik' => '2090237', 'nama' => 'GINTING WIDODO', 'status' => 'NST'],
                ['nik' => '12100127', 'nama' => 'GUNAWAN', 'status' => 'NST'],
                ['nik' => '12100072', 'nama' => 'HADI UTOMO', 'status' => 'NST'],
                ['nik' => '26079915', 'nama' => 'HALIM ARIL ADITYA', 'status' => 'MG'],
                ['nik' => '11100252', 'nama' => 'HAPID KAMALUDIN', 'status' => 'NST'],
                ['nik' => '25129918', 'nama' => 'HARBELLAN PAMUNGKAS S P', 'status' => 'MG'],
                ['nik' => '26059901', 'nama' => 'HARIS AL HAKIM', 'status' => 'MG'],
                ['nik' => '11080239', 'nama' => 'HASAN MA SUM', 'status' => 'NST'],
                ['nik' => '26029916', 'nama' => 'HASAN SAEPULLOH', 'status' => 'MG'],
                ['nik' => '26062403', 'nama' => 'HASBY MUBAROK', 'status' => 'NSK'],
                ['nik' => '7040013', 'nama' => 'HASTA ARI CANDRA PS', 'status' => 'NST'],
                ['nik' => '14090194', 'nama' => 'HERI HARYADI', 'status' => 'NST'],
                ['nik' => '12070017', 'nama' => 'HERI LASTONO', 'status' => 'NST'],
                ['nik' => '25090801', 'nama' => 'HERI SETIAWAN', 'status' => 'NSK'],
                ['nik' => '13070319', 'nama' => 'HERIYANTO', 'status' => 'NST'],
                ['nik' => '20060365', 'nama' => 'HERU BANDOWO', 'status' => 'SK'],
                ['nik' => '12120135', 'nama' => 'HERU BUDIANTO', 'status' => 'ST'],
                ['nik' => '11030294', 'nama' => 'IIR IRAWAN', 'status' => 'NST'],
                ['nik' => '14010183', 'nama' => 'IIS ROMADONA', 'status' => 'NST'],
                ['nik' => '26029920', 'nama' => 'ILHAM NURFATWA', 'status' => 'MG'],
                ['nik' => '25099913', 'nama' => 'ILYAS SAEFUL RAMDHANI', 'status' => 'MG'],
                ['nik' => '26029914', 'nama' => 'ILYAS SAEPULLOH', 'status' => 'MG'],
                ['nik' => '120212', 'nama' => 'INDRA MAULANA', 'status' => 'NST'],
                ['nik' => '25109914', 'nama' => 'IRZAFADIL ISNANTO', 'status' => 'MG'],
                ['nik' => '26049902', 'nama' => 'ISMAIL NUGROHO', 'status' => 'MG'],
                ['nik' => '12100076', 'nama' => 'JALASMAN', 'status' => 'NST'],
                ['nik' => '11090276', 'nama' => 'JAMALUDIN SIDIK', 'status' => 'NST'],
                ['nik' => '20010359', 'nama' => 'JODI DERMAWAN', 'status' => 'NST'],
                ['nik' => '13100175', 'nama' => 'JOKO HERIYANTO', 'status' => 'NST'],
                ['nik' => '12100077', 'nama' => 'JOKO PURNOMO', 'status' => 'NST'],
                ['nik' => '14010182', 'nama' => 'JOKO SAPARI', 'status' => 'NST'],
                ['nik' => '26079912', 'nama' => 'JUHRO', 'status' => 'MG'],
                ['nik' => '26049914', 'nama' => 'JULIUS ALBERTHO S', 'status' => 'MG'],
                ['nik' => '12120138', 'nama' => 'KALYUBI', 'status' => 'NST'],
                ['nik' => '25062507', 'nama' => 'KAMALUDIN', 'status' => 'NSK'],
                ['nik' => '26069930', 'nama' => 'KARNO', 'status' => 'MG'],
                ['nik' => '26069935', 'nama' => 'KARSA', 'status' => 'MG'],
                ['nik' => '25099911', 'nama' => 'KELVIN FERLI SETYA N', 'status' => 'MG'],
                ['nik' => '12100079', 'nama' => 'KHAERUL ANWAR', 'status' => 'NST'],
                ['nik' => '26069914', 'nama' => 'KHARIS NIMATULLOH', 'status' => 'MG'],
                ['nik' => '24100203', 'nama' => 'KHISYAN RABBUL INSANNI', 'status' => 'NSK'],
                ['nik' => '24119918', 'nama' => 'KHOERUL ISMAIL', 'status' => 'MG'],
                ['nik' => '26039915', 'nama' => 'KIKI DARMAWAN', 'status' => 'MG'],
                ['nik' => '12100081', 'nama' => 'KOMARUDIN', 'status' => 'NST'],
                ['nik' => '26069917', 'nama' => 'KUSTARA', 'status' => 'MG'],
                ['nik' => '26019901', 'nama' => 'LATIP SYAEFULOH', 'status' => 'MG'],
                ['nik' => '3080020', 'nama' => 'LENA RIYANI', 'status' => 'NST'],
                ['nik' => '25079901', 'nama' => 'LUCKY AJI PRATAMA', 'status' => 'MG'],
                ['nik' => '12100083', 'nama' => 'LUKI MULYANA', 'status' => 'NST'],
                ['nik' => '25119902', 'nama' => 'LUTFYANSYAH BOIRATAN', 'status' => 'MG'],
                ['nik' => '25099910', 'nama' => 'M. SAHAL ARASID', 'status' => 'MG'],
                ['nik' => '25099920', 'nama' => 'MAHIFAL YOFA JANUAR', 'status' => 'MG'],
                ['nik' => '97030066', 'nama' => 'MAKMURIDIN', 'status' => 'NST'],
                ['nik' => '40173', 'nama' => 'MANDONO', 'status' => 'NST'],
                ['nik' => '13090168', 'nama' => 'MANSUR', 'status' => 'NST'],
                ['nik' => '99090120', 'nama' => 'MARINO', 'status' => 'NST'],
                ['nik' => '11080278', 'nama' => 'MARPA I KHOERUL UMAM', 'status' => 'NST'],
                ['nik' => '12100110', 'nama' => 'MARTIN DWI SUSILO', 'status' => 'NST'],
                ['nik' => '26059904', 'nama' => 'MARWAN', 'status' => 'MG'],
                ['nik' => '13070160', 'nama' => 'MARWANTO', 'status' => 'NST'],
                ['nik' => '26042803', 'nama' => 'MARYADI', 'status' => 'NSK'],
                ['nik' => '99090116', 'nama' => 'MARYONO', 'status' => 'NST'],
                ['nik' => '26069908', 'nama' => 'MAULANA FADILAH AWSAR', 'status' => 'MG'],
                ['nik' => '26039914', 'nama' => 'MAULANA IBRAHIM', 'status' => 'MG'],
                ['nik' => '11090215', 'nama' => 'MAULANA YUSUF', 'status' => 'NST'],
                ['nik' => '12050312', 'nama' => 'MEGA KARISTIAWAN', 'status' => 'NST'],
                ['nik' => '26049911', 'nama' => 'MICHAEL LOVEL MAITIMU', 'status' => 'MG'],
                ['nik' => '26069922', 'nama' => 'MOCHAMAD ISHAK FIRMANSYAH', 'status' => 'MG'],
                ['nik' => '25109902', 'nama' => 'MOCHAMAD RIZKY ALFIANSYAH', 'status' => 'MG'],
                ['nik' => '5090018', 'nama' => 'MOH AHMAD SAMSURI', 'status' => 'NST'],
                ['nik' => '12020306', 'nama' => 'MOH MAIMUN', 'status' => 'NST'],
                ['nik' => '26069910', 'nama' => 'MOH. ABNI IQSAN SAPUTRA', 'status' => 'MG'],
                ['nik' => '26079914', 'nama' => 'MOHAMAD FAREL EPRILIANO', 'status' => 'MG'],
                ['nik' => '24090502', 'nama' => 'MOHAMAD NAUFAL RIFQI PRIATNA', 'status' => 'NSK'],
                ['nik' => '24051003', 'nama' => 'MOHAMAD SODIK', 'status' => 'NSK'],
                ['nik' => '25079922', 'nama' => 'MOHAMAD WAHYUDI', 'status' => 'MG'],
                ['nik' => '25069941', 'nama' => 'MOHAMMAD BA ITSUL HAQ', 'status' => 'MG'],
                ['nik' => '23083002', 'nama' => 'MOHAMMAD MULYADI', 'status' => 'NSK'],
                ['nik' => '26079936', 'nama' => 'MUHAMAD ABDUL AZIZ', 'status' => 'MG'],
                ['nik' => '25060202', 'nama' => 'MUHAMAD ANDREAN SAEFULLOH', 'status' => 'NSK'],
                ['nik' => '25111903', 'nama' => 'MUHAMAD CHARIRI', 'status' => 'NSK'],
                ['nik' => '25109916', 'nama' => 'MUHAMAD FABIYANSYAH', 'status' => 'MG'],
                ['nik' => '26069937', 'nama' => 'MUHAMAD FAJAR SULAEMAN', 'status' => 'MG'],
                ['nik' => '25079911', 'nama' => 'MUHAMAD FARHAN', 'status' => 'MG'],
                ['nik' => '25090391', 'nama' => 'MUHAMAD FIRDAUS', 'status' => 'NST'],
                ['nik' => '12040008', 'nama' => 'MUHAMAD GUNAWAN', 'status' => 'NST'],
                ['nik' => '11100280', 'nama' => 'MUHAMAD HADI MAKSUDI', 'status' => 'NST'],
                ['nik' => '26059922', 'nama' => 'MUHAMAD KADAFI FATURAHMAN', 'status' => 'MG'],
                ['nik' => '26069927', 'nama' => 'MUHAMAD RAFLI ALBAR', 'status' => 'MG'],
                ['nik' => '26069905', 'nama' => 'MUHAMAD RAFLY SANJAYA', 'status' => 'MG'],
                ['nik' => '23030801', 'nama' => 'MUHAMAD RAMA', 'status' => 'NSK'],
                ['nik' => '26069912', 'nama' => 'MUHAMAD REZA', 'status' => 'MG'],
                ['nik' => '11100234', 'nama' => 'MUHAMAD RIDWAN SETIAWAN', 'status' => 'NST'],
                ['nik' => '26069936', 'nama' => 'MUHAMAD RIFKI WIJAYA', 'status' => 'MG'],
                ['nik' => '26059916', 'nama' => 'MUHAMAD RIFQI', 'status' => 'MG'],
                ['nik' => '26029919', 'nama' => 'MUHAMAD RIKI ANDRIAN', 'status' => 'MG'],
                ['nik' => '25111102', 'nama' => 'MUHAMAD RIVALDI', 'status' => 'NSK'],
                ['nik' => '25069927', 'nama' => 'MUHAMAD SADAM', 'status' => 'MG'],
                ['nik' => '26069926', 'nama' => 'MUHAMAD SOLEH', 'status' => 'MG'],
                ['nik' => '12090030', 'nama' => 'MUHAMAD SUAEB', 'status' => 'NST'],
                ['nik' => '25099908', 'nama' => 'MUHAMMAD ABDAN KHAIR R', 'status' => 'MG'],
                ['nik' => '26059912', 'nama' => 'MUHAMMAD ADIB ZAINUL M', 'status' => 'MG'],
                ['nik' => '26079919', 'nama' => 'MUHAMMAD ADNAN AL FAKIH', 'status' => 'MG'],
                ['nik' => '25079919', 'nama' => 'MUHAMMAD AFIF FAUZI', 'status' => 'MG'],
                ['nik' => '26039905', 'nama' => 'MUHAMMAD AL HAVIZ SYADI I', 'status' => 'MG'],
                ['nik' => '26079918', 'nama' => 'MUHAMMAD ALAIK BAIHAQI', 'status' => 'MG'],
                ['nik' => '25099906', 'nama' => 'MUHAMMAD APRIANSYAH', 'status' => 'MG'],
                ['nik' => '25059916', 'nama' => 'MUHAMMAD BUKHORI', 'status' => 'MG'],
                ['nik' => '25099901', 'nama' => 'MUHAMMAD FACHHRY FADHILLAH', 'status' => 'MG'],
                ['nik' => '25099912', 'nama' => 'MUHAMMAD FARIS RAMADHAN', 'status' => 'MG'],
                ['nik' => '26069906', 'nama' => 'MUHAMMAD FIRLI FABILLAH', 'status' => 'MG'],
                ['nik' => '25099919', 'nama' => 'MUHAMMAD GESIT OKTAVIAN', 'status' => 'MG'],
                ['nik' => '26029918', 'nama' => 'MUHAMMAD HASANUDDIN. A. W', 'status' => 'MG'],
                ['nik' => '26079913', 'nama' => 'MUHAMMAD ILHAM NURKHOLIQ', 'status' => 'MG'],
                ['nik' => '25129911', 'nama' => 'MUHAMMAD ILMAN NAFIA', 'status' => 'MG'],
                ['nik' => '26069924', 'nama' => 'MUHAMMAD IQBAL ANDARA', 'status' => 'MG'],
                ['nik' => '25119903', 'nama' => 'MUHAMMAD IQBAL KUSUMA', 'status' => 'MG'],
                ['nik' => '25112604', 'nama' => 'MUHAMMAD JALALUDIN', 'status' => 'NSK'],
                ['nik' => '12100119', 'nama' => 'MUHAMMAD KHANAFI', 'status' => 'NST'],
                ['nik' => '26079908', 'nama' => 'MUHAMMAD RAIHAN', 'status' => 'MG'],
                ['nik' => '26029917', 'nama' => 'MUHAMMAD RAIKHAN ALFAQIH', 'status' => 'MG'],
                ['nik' => '26079910', 'nama' => 'MUHAMMAD UMAIR', 'status' => 'MG'],
                ['nik' => '26059921', 'nama' => 'MUHAMMAD YAZRIL', 'status' => 'MG'],
                ['nik' => '30162', 'nama' => 'MUHAMMAD YUSUF', 'status' => 'NST'],
                ['nik' => '26059917', 'nama' => 'MUJIB AMRILLAH', 'status' => 'MG'],
                ['nik' => '9030004', 'nama' => 'MUJIONO', 'status' => 'NST'],
                ['nik' => '25102101', 'nama' => 'MUKTI BAYU SETO', 'status' => 'NSK'],
                ['nik' => '12100088', 'nama' => 'MULYADI', 'status' => 'NST'],
                ['nik' => '12010269', 'nama' => 'MUNARYO', 'status' => 'NST'],
                ['nik' => '11120244', 'nama' => 'NANANG SUNANDI', 'status' => 'NST'],
                ['nik' => '99110135', 'nama' => 'NARTO ISWORO', 'status' => 'NST'],
                ['nik' => '99070099', 'nama' => 'NASAR', 'status' => 'NST'],
                ['nik' => '25089903', 'nama' => 'NASIM', 'status' => 'MG'],
                ['nik' => '25129907', 'nama' => 'NASRULLAH ALDHIANSYAH', 'status' => 'MG'],
                ['nik' => '26039904', 'nama' => 'NICOLA DEZA ALANUARI', 'status' => 'MG'],
                ['nik' => '12100113', 'nama' => 'NUR HASANAH', 'status' => 'NST'],
                ['nik' => '7100015', 'nama' => 'NURDIN', 'status' => 'NST'],
                ['nik' => '12100090', 'nama' => 'NURHASANUDIN', 'status' => 'NST'],
                ['nik' => '11090213', 'nama' => 'NURHAYATI', 'status' => 'NST'],
                ['nik' => '23101103', 'nama' => 'NURHIDAYAT', 'status' => 'NSK'],
                ['nik' => '26039911', 'nama' => 'OMARA ZAIZAZIL', 'status' => 'MG'],
                ['nik' => '13070159', 'nama' => 'OMAT KARUNIA', 'status' => 'NST'],
                ['nik' => '25110392', 'nama' => 'ORIS TRIANTO', 'status' => 'NST'],
                ['nik' => '12100055', 'nama' => 'OSHA RIZQIHADI YUNANTO', 'status' => 'NST'],
                ['nik' => '26039907', 'nama' => 'PALI FAJRI RHAMADAN', 'status' => 'MG'],
                ['nik' => '25109904', 'nama' => 'PAUZI HAMDANI', 'status' => 'MG'],
                ['nik' => '12100091', 'nama' => 'PRIHANTORO', 'status' => 'NST'],
                ['nik' => '11110253', 'nama' => 'PRIYO GUSTANTO', 'status' => 'NST'],
                ['nik' => '20160', 'nama' => 'RADIAWATI ANWAR', 'status' => 'NST'],
                ['nik' => '25129906', 'nama' => 'RAFI ABIAH RAMADAN', 'status' => 'MG'],
                ['nik' => '24031302', 'nama' => 'RAFLI MUHAMMAD RIZKI', 'status' => 'NSK'],
                ['nik' => '25089904', 'nama' => 'RAFLI PRASETIA', 'status' => 'MG'],
                ['nik' => '25109915', 'nama' => 'RAHMAT FARIS', 'status' => 'MG'],
                ['nik' => '12100092', 'nama' => 'RAHMAT WIDI WIDAYAT', 'status' => 'NST'],
                ['nik' => '26059918', 'nama' => 'RAIHAN JUNDI HANIVAL', 'status' => 'MG'],
                ['nik' => '25089902', 'nama' => 'RAJIF PUTRA PRADANA', 'status' => 'MG'],
                ['nik' => '26079907', 'nama' => 'RAKHA IRWANSYAH', 'status' => 'MG'],
                ['nik' => '1010214', 'nama' => 'RAMDANI', 'status' => 'NST'],
                ['nik' => '26069918', 'nama' => 'RAMDANI', 'status' => 'MG'],
                ['nik' => '26039901', 'nama' => 'REFAL SETIAWAN', 'status' => 'MG'],
                ['nik' => '25099903', 'nama' => 'RENDI BUVAN', 'status' => 'MG'],
                ['nik' => '14070193', 'nama' => 'RENDI SATYA PERMANA', 'status' => 'NST'],
                ['nik' => '11100275', 'nama' => 'RETNO PERMANA', 'status' => 'NST'],
                ['nik' => '26039920', 'nama' => 'REVI ADITYA', 'status' => 'MG'],
                ['nik' => '24123105', 'nama' => 'REZA SUPRIANDI', 'status' => 'NSK'],
                ['nik' => '25119908', 'nama' => 'RICKO HERDIYAN SYAPUTRA', 'status' => 'MG'],
                ['nik' => '25109913', 'nama' => 'RIDHO FAUZI', 'status' => 'MG'],
                ['nik' => '26059905', 'nama' => 'RIDJWAN TRISNANTO', 'status' => 'MG'],
                ['nik' => '26029910', 'nama' => 'RIFAL MAULANA', 'status' => 'MG'],
                ['nik' => '26069925', 'nama' => 'RIFAL OGIANA', 'status' => 'MG'],
                ['nik' => '25129908', 'nama' => 'RIFKI JANUARDY', 'status' => 'MG'],
                ['nik' => '25109906', 'nama' => 'RIFKY NOFAL ALI T', 'status' => 'MG'],
                ['nik' => '26039903', 'nama' => 'RIKAL FAHMI RAMADHAN', 'status' => 'MG'],
                ['nik' => '12100115', 'nama' => 'RISYANTO', 'status' => 'NST'],
                ['nik' => '25099905', 'nama' => 'RIZAL FATAHULLOH F', 'status' => 'MG'],
                ['nik' => '26059909', 'nama' => 'RIZAL WAHYU PURNOMO', 'status' => 'MG'],
                ['nik' => '26059902', 'nama' => 'RIZKI ROMADON', 'status' => 'MG'],
                ['nik' => '25079917', 'nama' => 'RIZKY ARDIANSYAH PUTRA', 'status' => 'MG'],
                ['nik' => '26039922', 'nama' => 'RIZKY ARWENDI SAPUTRA P', 'status' => 'MG'],
                ['nik' => '26029908', 'nama' => 'RIZKY FAUZI', 'status' => 'MG'],
                ['nik' => '26069903', 'nama' => 'RIZKY MAULANA ARRASYID', 'status' => 'MG'],
                ['nik' => '11090214', 'nama' => 'RIZKY SETIAWAN', 'status' => 'NST'],
                ['nik' => '26069915', 'nama' => 'RIZKY TANGGUH FIRMANSYAH', 'status' => 'MG'],
                ['nik' => '11090232', 'nama' => 'ROHIM FATURAHMAN', 'status' => 'NST'],
                ['nik' => '12120144', 'nama' => 'ROHMAT', 'status' => 'NST'],
                ['nik' => '26029906', 'nama' => 'ROHMAT HIDAYAT', 'status' => 'MG'],
                ['nik' => '12090318', 'nama' => 'RUDI KRISTIANTO', 'status' => 'NST'],
                ['nik' => '11110245', 'nama' => 'RUDI SURIPTO', 'status' => 'NST'],
                ['nik' => '12100128', 'nama' => 'RUDIYANTO', 'status' => 'NST'],
                ['nik' => '25119918', 'nama' => 'RYAN HIDAYATTULLOH', 'status' => 'MG'],
                ['nik' => '25119911', 'nama' => 'RYANDANA HERLAMBANG', 'status' => 'MG'],
                ['nik' => '12100042', 'nama' => 'SADAN', 'status' => 'NST'],
                ['nik' => '25129913', 'nama' => 'SAEFULLOH YUSUF', 'status' => 'MG'],
                ['nik' => '25119912', 'nama' => 'SAHRUL', 'status' => 'MG'],
                ['nik' => '26059907', 'nama' => 'SAHRUL WINAWAN ROHMAN', 'status' => 'MG'],
                ['nik' => '11110274', 'nama' => 'SAMSUDIN', 'status' => 'NST'],
                ['nik' => '26049903', 'nama' => 'SAMUEL JHON RYAN SIAHAAN', 'status' => 'MG'],
                ['nik' => '25079921', 'nama' => 'SANDI DWI ANDIKA', 'status' => 'MG'],
                ['nik' => '12080027', 'nama' => 'SANDIKO', 'status' => 'NST'],
                ['nik' => '10100287', 'nama' => 'SAPRUDIN', 'status' => 'NST'],
                ['nik' => '12100094', 'nama' => 'SARIPUDIN', 'status' => 'NST'],
                ['nik' => '26029903', 'nama' => 'SENDI FIRMANSYAH', 'status' => 'MG'],
                ['nik' => '25119906', 'nama' => 'SENDY ALI FATUR RAHMAN', 'status' => 'MG'],
                ['nik' => '8090034', 'nama' => 'SENOKY PRAYITNO', 'status' => 'NST'],
                ['nik' => '26059924', 'nama' => 'SEPTIAN DWI HARTANTO', 'status' => 'MG'],
                ['nik' => '26049913', 'nama' => 'SOFIYAN BAHRI', 'status' => 'MG'],
                ['nik' => '99090119', 'nama' => 'SRI MARYATI', 'status' => 'NST'],
                ['nik' => '7070014', 'nama' => 'SRI MULYATI', 'status' => 'NST'],
                ['nik' => '99090114', 'nama' => 'SUBUH SARWOKO', 'status' => 'NST'],
                ['nik' => '12080024', 'nama' => 'SUDARYANTO', 'status' => 'NST'],
                ['nik' => '13070320', 'nama' => 'SUGENG PUJI RAHARJO', 'status' => 'NST'],
                ['nik' => '9030006', 'nama' => 'SUGIYANTA', 'status' => 'NST'],
                ['nik' => '13100170', 'nama' => 'SUHARYANTI', 'status' => 'NST'],
                ['nik' => '26069929', 'nama' => 'SUHENDAR', 'status' => 'MG'],
                ['nik' => '26042102', 'nama' => 'SUHERMAN', 'status' => 'NSK'],
                ['nik' => '5040008', 'nama' => 'SUHERMANTO', 'status' => 'NST'],
                ['nik' => '50177', 'nama' => 'SUKARDI S.', 'status' => 'NST'],
                ['nik' => '12100043', 'nama' => 'SUKARI', 'status' => 'NST'],
                ['nik' => '12100133', 'nama' => 'SUKARJO', 'status' => 'NST'],
                ['nik' => '26069913', 'nama' => 'SULTAN FIRDAUS ABDURAHMAN', 'status' => 'MG'],
                ['nik' => '99070097', 'nama' => 'SUMERI', 'status' => 'NST'],
                ['nik' => '2120249', 'nama' => 'SUNARDI', 'status' => 'NST'],
                ['nik' => '97030070', 'nama' => 'SUPARDI', 'status' => 'NST'],
                ['nik' => '11070249', 'nama' => 'SUPARLAN', 'status' => 'NST'],
                ['nik' => '12080028', 'nama' => 'SUPARYO', 'status' => 'NST'],
                ['nik' => '26029913', 'nama' => 'SUPRIATNA', 'status' => 'MG'],
                ['nik' => '12100098', 'nama' => 'SUPRIYADI', 'status' => 'NST'],
                ['nik' => '12100097', 'nama' => 'SUPRIYADI', 'status' => 'NST'],
                ['nik' => '12100099', 'nama' => 'SUSANTO', 'status' => 'NST'],
                ['nik' => '12100100', 'nama' => 'SUTADI', 'status' => 'NST'],
                ['nik' => '12010279', 'nama' => 'SUTIONO', 'status' => 'NST'],
                ['nik' => '120206', 'nama' => 'SUTISNO', 'status' => 'NST'],
                ['nik' => '8090030', 'nama' => 'SUTOPO', 'status' => 'NST'],
                ['nik' => '99060091', 'nama' => 'SUTRISNO', 'status' => 'NST'],
                ['nik' => '12100111', 'nama' => 'SYAMSUL MA ARIF', 'status' => 'NST'],
                ['nik' => '26039923', 'nama' => 'SYAPA NURADIANSYAH', 'status' => 'MG'],
                ['nik' => '25063008', 'nama' => 'SYARIF DEVA PUTRA', 'status' => 'NSK'],
                ['nik' => '5020005', 'nama' => 'SYARIF RACHMAN', 'status' => 'NST'],
                ['nik' => '25111101', 'nama' => 'TAUFIK HIDAYAT', 'status' => 'NSK'],
                ['nik' => '12030316', 'nama' => 'TEDDY IRAWAN', 'status' => 'NST'],
                ['nik' => '25119916', 'nama' => 'TEDDY MAULANA', 'status' => 'MG'],
                ['nik' => '11100228', 'nama' => 'TEGUH SANJAYA', 'status' => 'NST'],
                ['nik' => '12100101', 'nama' => 'TEGUH WIBAWA', 'status' => 'NST'],
                ['nik' => '25109905', 'nama' => 'TOMY RAHMAT KURNIAWAN', 'status' => 'MG'],
                ['nik' => '97060074', 'nama' => 'TUGINO', 'status' => 'NST'],
                ['nik' => '3060014', 'nama' => 'TUSIN SUPIANDI', 'status' => 'NST'],
                ['nik' => '2120244', 'nama' => 'TUSLIKHAH', 'status' => 'NST'],
                ['nik' => '26069932', 'nama' => 'UJANG ANDRIYANTO', 'status' => 'MG'],
                ['nik' => '25039902', 'nama' => 'WAHYU RYAN', 'status' => 'MG'],
                ['nik' => '9030005', 'nama' => 'WAHYU TANOTO', 'status' => 'NST'],
                ['nik' => '12100103', 'nama' => 'WAHYUDI', 'status' => 'NST'],
                ['nik' => '11120272', 'nama' => 'WAHYUDIN', 'status' => 'NST'],
                ['nik' => '12070016', 'nama' => 'WALOYO', 'status' => 'NST'],
                ['nik' => '10143', 'nama' => 'WARSO', 'status' => 'NST'],
                ['nik' => '25082601', 'nama' => 'WIBI PRIYO LAKSONO', 'status' => 'NSK'],
                ['nik' => '12050314', 'nama' => 'WISNU RIYADI', 'status' => 'NST'],
                ['nik' => '23051001', 'nama' => 'YANA SURYANA', 'status' => 'NSK'],
                ['nik' => '26059920', 'nama' => 'YASIN NUR HALIM', 'status' => 'MG'],
                ['nik' => '12100107', 'nama' => 'YOHANA', 'status' => 'NST'],
                ['nik' => '26029902', 'nama' => 'YUDHI FAREIL PRAMANA', 'status' => 'MG'],
                ['nik' => '20154', 'nama' => 'YUNIYANTO', 'status' => 'NST'],
                ['nik' => '26059925', 'nama' => 'YUSEP SAEFUL MIQDAR', 'status' => 'MG'],
                ['nik' => '26039917', 'nama' => 'YUSUP NURFAJAR H', 'status' => 'MG'],
                ['nik' => '99110138', 'nama' => 'YUYU WAHYUDIN', 'status' => 'NST'],
                ['nik' => '26059919', 'nama' => 'ZAHA AA ALLAIKA MUFID', 'status' => 'MG'],
                ['nik' => '26059913', 'nama' => 'ZAHRA NAUFAL NIZAR AL R', 'status' => 'MG'],
                ['nik' => '25099922', 'nama' => 'ZATTA PUTRA PAMUNGKAS', 'status' => 'MG'],
                ['nik' => '25129902', 'nama' => 'ZIDANE ARYA PASHA', 'status' => 'MG'],
            ],
            'PPR' => [
                ['nik' => '13100173', 'nama' => 'AGUNG NUGROHO', 'status' => 'NST'],
                ['nik' => '5070016', 'nama' => 'AGUS RIYADI', 'status' => 'NST'],
                ['nik' => '12100126', 'nama' => 'DODI IRAWAN', 'status' => 'NST'],
                ['nik' => '12100068', 'nama' => 'DODO WIDODO', 'status' => 'NST'],
                ['nik' => '14100203', 'nama' => 'EKO MUHAMMAD TRIAS PURWANTA', 'status' => 'NST'],
                ['nik' => '11120222', 'nama' => 'EKO SISWOYO', 'status' => 'NST'],
                ['nik' => '12100071', 'nama' => 'FERY ANDIKA', 'status' => 'NST'],
                ['nik' => '13090167', 'nama' => 'HASANUDIN', 'status' => 'NST'],
                ['nik' => '23120401', 'nama' => 'IKHFAN DERYAN', 'status' => 'NSK'],
                ['nik' => '11080205', 'nama' => 'IRPAN HARAPAN', 'status' => 'NST'],
                ['nik' => '13060317', 'nama' => 'IWAN APRIAWAN', 'status' => 'NST'],
                ['nik' => '12020006', 'nama' => 'JOKO TRI BROTO', 'status' => 'NST'],
                ['nik' => '9020002', 'nama' => 'JONIH', 'status' => 'NST'],
                ['nik' => '99100131', 'nama' => 'JULIYANTO', 'status' => 'NST'],
                ['nik' => '12100080', 'nama' => 'KHAERUL FAHRI', 'status' => 'NST'],
                ['nik' => '23070383', 'nama' => 'KIRNO', 'status' => 'SK'],
                ['nik' => '11100292', 'nama' => 'M. AMIR HAMZAH', 'status' => 'NST'],
                ['nik' => '92070022', 'nama' => 'MARYONO', 'status' => 'NST'],
                ['nik' => '12100086', 'nama' => 'MISGIARTO', 'status' => 'NST'],
                ['nik' => '12100087', 'nama' => 'MUHAMMAD ACHIRUL', 'status' => 'NST'],
                ['nik' => '11100270', 'nama' => 'NANA ROHANA', 'status' => 'NST'],
                ['nik' => '99110134', 'nama' => 'NGADIYO', 'status' => 'NST'],
                ['nik' => '3020006', 'nama' => 'OTONG SURIPTO', 'status' => 'NST'],
                ['nik' => '11100268', 'nama' => 'PAIMAN', 'status' => 'NST'],
                ['nik' => '14020185', 'nama' => 'PARIYATIN', 'status' => 'NST'],
                ['nik' => '1010221', 'nama' => 'PUJI SETIYANINGSIH', 'status' => 'NST'],
                ['nik' => '25020388', 'nama' => 'RIDWAN SALIM', 'status' => 'NST'],
                ['nik' => '13090166', 'nama' => 'RISKA HARIYANTI', 'status' => 'NST'],
                ['nik' => '12100093', 'nama' => 'RM IKMATULOH', 'status' => 'NST'],
                ['nik' => '12110129', 'nama' => 'SAEPUDIN', 'status' => 'NST'],
                ['nik' => '12010283', 'nama' => 'SUBUR SLAMET', 'status' => 'NST'],
                ['nik' => '12010285', 'nama' => 'SYARIPUDIN', 'status' => 'NST'],
                ['nik' => '15010212', 'nama' => 'THORI AFRIANTO', 'status' => 'NST'],
                ['nik' => '6120017', 'nama' => 'WIJANARKO', 'status' => 'NST'],
                ['nik' => '12100106', 'nama' => 'YANTO SAPUTRA', 'status' => 'NST'],
            ],
            'MTC' => [
                ['nik' => '11090271', 'nama' => 'ACEP SUHANTA', 'status' => 'NST'],
                ['nik' => '24122303', 'nama' => 'ARI AHMAD', 'status' => 'NSK'],
                ['nik' => '11100229', 'nama' => 'DENI KURNIAWAN', 'status' => 'NST'],
                ['nik' => '9010001', 'nama' => 'DENI PURNAMA', 'status' => 'NST'],
                ['nik' => '20030362', 'nama' => 'DIMAZ RIZKY PRATAMA', 'status' => 'NST'],
                ['nik' => '13060318', 'nama' => 'DOMI SUMARLIN', 'status' => 'NST'],
                ['nik' => '12100045', 'nama' => 'DWI ATMOKO', 'status' => 'NST'],
                ['nik' => '12100069', 'nama' => 'DWIANTO', 'status' => 'NST'],
                ['nik' => '11090246', 'nama' => 'EKA RIYANTO', 'status' => 'NST'],
                ['nik' => '8020020', 'nama' => 'ELI WAHYONO', 'status' => 'NST'],
                ['nik' => '11110235', 'nama' => 'EMAN SULAEMAN', 'status' => 'NST'],
                ['nik' => '12100125', 'nama' => 'ENDANG SUHERI', 'status' => 'NST'],
                ['nik' => '24091704', 'nama' => 'FAKHRI ARYA PRATAMA', 'status' => 'NSK'],
                ['nik' => '11030231', 'nama' => 'HERMAWAN SUPENDI', 'status' => 'NST'],
                ['nik' => '12100122', 'nama' => 'IDRIS APANDI', 'status' => 'NST'],
                ['nik' => '9070011', 'nama' => 'INDRA RUSDIANTO', 'status' => 'NST'],
                ['nik' => '12100078', 'nama' => 'JOKO SEPTIYONO', 'status' => 'NST'],
                ['nik' => '13070156', 'nama' => 'M. AGUS SUPRIYADI', 'status' => 'NST'],
                ['nik' => '12100124', 'nama' => 'MUHAMMAD TOMI', 'status' => 'NST'],
                ['nik' => '8060024', 'nama' => 'MURSITO', 'status' => 'NST'],
                ['nik' => '21080374', 'nama' => 'NURHASAN', 'status' => 'NST'],
                ['nik' => '26070395', 'nama' => 'RIWANI', 'status' => 'SK'],
                ['nik' => '24100404', 'nama' => 'RIZQI RUDI FAYYADH', 'status' => 'NSK'],
                ['nik' => '11010009', 'nama' => 'RM NABIL', 'status' => 'NST'],
                ['nik' => '11070288', 'nama' => 'SAMSUL ARIPIN', 'status' => 'NST'],
                ['nik' => '11110265', 'nama' => 'SANUSI RUSLANI', 'status' => 'NST'],
                ['nik' => '12100046', 'nama' => 'SLAMET RIYADI', 'status' => 'NST'],
                ['nik' => '11080023', 'nama' => 'SUDIAMAN', 'status' => 'NST'],
                ['nik' => '11010010', 'nama' => 'TRI YULIYANTO', 'status' => 'NST'],
                ['nik' => '12100105', 'nama' => 'WIYANTO', 'status' => 'NST'],
            ],
        ];

        $totalDibuat = 0;

        foreach ($dataKaryawan as $kode => $daftarKaryawan) {
            $departement = Departement::firstOrCreate(
                ['kode_departement' => $kode],
                ['nama_departement' => $departemenNama[$kode]]
            );

            $kompetensiIds = Kompetensi::whereHas('departements', function ($q) use ($departement) {
                $q->where('departements.id', $departement->id);
            })->pluck('id');

            foreach ($daftarKaryawan as $item) {
                $karyawan = User::updateOrCreate(
                    ['nik' => $item['nik']],
                    [
                        'name' => $item['nama'],
                        'email' => $item['nik'] . '@dasawindu.co.id',
                        'password' => Hash::make('password123'),
                        'role' => 'karyawan',
                        'departement_id' => $departement->id,
                        'atasan_id' => $atasan->id,
                        'status' => $item['status'],
                    ]
                );

                $now = now();
                $pivotRows = $kompetensiIds->map(fn ($kompetensiId) => [
                    'user_id' => $karyawan->id,
                    'kompetensi_id' => $kompetensiId,
                    'actual_level' => 0,
                    'evaluated_by' => null,
                    'evaluated_at' => null,
                    'created_at' => $now,
                    'updated_at' => $now,
                ])->toArray();

                if (! empty($pivotRows)) {
                    DB::table('kompetensi_user')->upsert(
                        $pivotRows,
                        ['user_id', 'kompetensi_id'],
                        []
                    );
                }

                $totalDibuat++;
            }

            $this->command->info("Departemen {$kode} ({$departemenNama[$kode]}): " . count($daftarKaryawan) . ' karyawan.');
        }

        $this->command->info("Total {$totalDibuat} karyawan asli berhasil dibuat/diperbarui.");
    }
}